In [16]:
chemin = "/home/josheren/Downloads/donnees_agriculture.csv"

In [17]:
import pandas as pd

df = pd.read_csv(chemin)

df.head()

,id,culture,region,surface_ha,rendement_t_ha,engrais_kg,irrigation,prix_tonne,commentaire,date,nb_ligne
0,1,Maïs,Nord,10.0,"2,5",50.0,Oui,120.0,-,2020-06-01 00:00:00,1
1,2,Riz,Sud,15.0,3,60.0,Non,140.0,-,2020-06-01 00:00:00,2
2,3,Mil,Est,12.0,"1,8",40.0,Oui,100.0,-,2020-06-01 00:00:00,3
3,4,Soja,Ouest,8.0,"2,2",55.0,Non,130.0,-,2020-06-01 00:00:00,4
4,5,Coton,Nord,20.0,"3,5",70.0,Oui,150.0,-,2020-06-01 00:00:00,5

In [18]:
df.dtypes

id                  int64
culture            object
region             object
surface_ha        float64
rendement_t_ha     object
engrais_kg        float64
irrigation         object
prix_tonne        float64
commentaire        object
date               object
nb_ligne            int64
dtype: object

In [23]:
df.isnull().sum()

id                0
culture           0
region            0
surface_ha        2
rendement_t_ha    1
engrais_kg        1
irrigation        0
prix_tonne        1
commentaire       0
date              0
nb_ligne          0
dtype: int64

In [20]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
dtype: bool

In [21]:
df["surface_ha"].mean()

np.float64(13.6)

In [22]:
df

,id,culture,region,surface_ha,rendement_t_ha,engrais_kg,irrigation,prix_tonne,commentaire,date,nb_ligne
0,1,Maïs,Nord,10.0,"2,5",50.0,Oui,120.0,-,2020-06-01 00:00:00,1
1,2,Riz,Sud,15.0,3,60.0,Non,140.0,-,2020-06-01 00:00:00,2
2,3,Mil,Est,12.0,"1,8",40.0,Oui,100.0,-,2020-06-01 00:00:00,3
3,4,Soja,Ouest,8.0,"2,2",55.0,Non,130.0,-,2020-06-01 00:00:00,4
4,5,Coton,Nord,20.0,"3,5",70.0,Oui,150.0,-,2020-06-01 00:00:00,5
5,6,Maïs,Sud,10.0,"2,5",50.0,Oui,120.0,-,2021-06-01 00:00:00,6
6,7,Riz,Est,NaN,3,60.0,Non,140.0,-,2021-06-01 00:00:00,7
7,8,Mil,Ouest,7.0,NaN,40.0,Oui,100.0,-,2021-06-01 00:00:00,8
8,9,Soja,Nord,25.0,"2,1",55.0,Non,130.0,-,2021-06-01 00:00:00,9
9,10,Coton,Sud,18.0,"3,6",NaN,Oui,150.0,-,2021-06-01 00:00:00,10
10,11,Maïs,Nord,10.0,"2,5",50.0,Oui,120.0,-,2022-06-01 00:00:00,11
11,12,Riz,Sud,15.0,3,60.0,Non,140.0,-,2022-06-01 00:00:00,12
12,13,Mil,Est,12.0,"1,8",40.0,Oui,NaN,-,2022-06-01 00:00:00,13
13,14,Soja,Ouest,NaN,"2,2",55.0,Non,130.0,-,2022-06-01 00:00:00,14
14,15,Coton,Nord,20.0,"3,5",70.0,Oui,150.0,-,2022-06-01 00:00:00,15
15,3,Mil,Est,12.0,"1,8",40.0,Oui,100.0,-,2020-06-01 00:00:00,16
16,6,Maïs,Sud,10.0,"2,5",50.0,Oui,120.0,-,2021-06-01 00:00:00,17

In [50]:
print(df["rendement_t_ha"].dtypes)

object

In [49]:
mean_surface = df["surface_ha"].mean()
mean_surface

df["surface_ha"] = df["surface_ha"].fillna(mean_surface)

df

,id,culture,region,surface_ha,rendement_t_ha,engrais_kg,irrigation,prix_tonne,commentaire,date,nb_ligne
0,1,Maïs,Nord,10.0,"2,5",50.0,Oui,120.0,-,2020-06-01 00:00:00,1
1,2,Riz,Sud,15.0,3,60.0,Non,140.0,-,2020-06-01 00:00:00,2
2,3,Mil,Est,12.0,"1,8",40.0,Oui,100.0,-,2020-06-01 00:00:00,3
3,4,Soja,Ouest,8.0,"2,2",55.0,Non,130.0,-,2020-06-01 00:00:00,4
4,5,Coton,Nord,20.0,"3,5",70.0,Oui,150.0,-,2020-06-01 00:00:00,5
5,6,Maïs,Sud,10.0,"2,5",50.0,Oui,120.0,-,2021-06-01 00:00:00,6
6,7,Riz,Est,13.6,3,60.0,Non,140.0,-,2021-06-01 00:00:00,7
7,8,Mil,Ouest,7.0,NaN,40.0,Oui,100.0,-,2021-06-01 00:00:00,8
8,9,Soja,Nord,25.0,"2,1",55.0,Non,130.0,-,2021-06-01 00:00:00,9
9,10,Coton,Sud,18.0,"3,6",NaN,Oui,150.0,-,2021-06-01 00:00:00,10
10,11,Maïs,Nord,10.0,"2,5",50.0,Oui,120.0,-,2022-06-01 00:00:00,11
11,12,Riz,Sud,15.0,3,60.0,Non,140.0,-,2022-06-01 00:00:00,12
12,13,Mil,Est,12.0,"1,8",40.0,Oui,NaN,-,2022-06-01 00:00:00,13
13,14,Soja,Ouest,13.6,"2,2",55.0,Non,130.0,-,2022-06-01 00:00:00,14
14,15,Coton,Nord,20.0,"3,5",70.0,Oui,150.0,-,2022-06-01 00:00:00,15
15,3,Mil,Est,12.0,"1,8",40.0,Oui,100.0,-,2020-06-01 00:00:00,16
16,6,Maïs,Sud,10.0,"2,5",50.0,Oui,120.0,-,2021-06-01 00:00:00,17

In [56]:
df["rendement_t_ha"] = df["rendement_t_ha"].replace(",", ".", regex=True)
df["rendement_t_ha"] = df["rendement_t_ha"].astype(float)
print(df["rendement_t_ha"].dtype)

df

float64

,id,culture,region,surface_ha,rendement_t_ha,engrais_kg,irrigation,prix_tonne,commentaire,date,nb_ligne
0,1,Maïs,Nord,10.0,2.5,50.0,Oui,120.0,-,2020-06-01 00:00:00,1
1,2,Riz,Sud,15.0,3.0,60.0,Non,140.0,-,2020-06-01 00:00:00,2
2,3,Mil,Est,12.0,1.8,40.0,Oui,100.0,-,2020-06-01 00:00:00,3
3,4,Soja,Ouest,8.0,2.2,55.0,Non,130.0,-,2020-06-01 00:00:00,4
4,5,Coton,Nord,20.0,3.5,70.0,Oui,150.0,-,2020-06-01 00:00:00,5
5,6,Maïs,Sud,10.0,2.5,50.0,Oui,120.0,-,2021-06-01 00:00:00,6
6,7,Riz,Est,13.6,3.0,60.0,Non,140.0,-,2021-06-01 00:00:00,7
7,8,Mil,Ouest,7.0,NaN,40.0,Oui,100.0,-,2021-06-01 00:00:00,8
8,9,Soja,Nord,25.0,2.1,55.0,Non,130.0,-,2021-06-01 00:00:00,9
9,10,Coton,Sud,18.0,3.6,NaN,Oui,150.0,-,2021-06-01 00:00:00,10
10,11,Maïs,Nord,10.0,2.5,50.0,Oui,120.0,-,2022-06-01 00:00:00,11
11,12,Riz,Sud,15.0,3.0,60.0,Non,140.0,-,2022-06-01 00:00:00,12
12,13,Mil,Est,12.0,1.8,40.0,Oui,NaN,-,2022-06-01 00:00:00,13
13,14,Soja,Ouest,13.6,2.2,55.0,Non,130.0,-,2022-06-01 00:00:00,14
14,15,Coton,Nord,20.0,3.5,70.0,Oui,150.0,-,2022-06-01 00:00:00,15
15,3,Mil,Est,12.0,1.8,40.0,Oui,100.0,-,2020-06-01 00:00:00,16
16,6,Maïs,Sud,10.0,2.5,50.0,Oui,120.0,-,2021-06-01 00:00:00,17

In [38]:
a = "22"
float(a.replace(",", "."))

22.0

In [35]:
df["rendement_t_ha"]

0     2,5
1       3
2     1,8
3     2,2
4     3,5
5     2,5
6       3
7     NaN
8     2,1
9     3,6
10    2,5
11      3
12    1,8
13    2,2
14    3,5
15    1,8
16    2,5
Name: rendement_t_ha, dtype: object